# render.yaml
# Configuration for deploying FastAPI app to Render

services:
  - type: web
    name: contract-review-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_contract_review:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    plan: free
    autoDeploy: true
